title: "Portfolio de Mathias GRADEK"
email: "mathias.gradek@epitech.eu"
description: "Futur développeur, passionné par le code et le basket"

baseurl: ""
url: "" 

collections:
  projects:
    output: true
    permalink: /projects/:name

sidebar_title: "Menu"
tagline: "J'aime beaucoup coder"